sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- yarn add polymer-cli
- polymer install --variants
script:
- xvfb-run ./node_modules/.bin/wct --root $TRAVIS_BUILD_DIR --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./node_modules/.bin/wct --root
  $TRAVIS_BUILD_DIR --plugin sauce --skip-plugin local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- ./scripts/ghp.sh
env:
  global:
  - secure: lKsAF30Oot4of/oCR6l9Cmv0HV6R44PKM72tIlAbuhfiHEucui/pJDDUdT4Fefe5IuKn6tCtYjW4O+H980HoPqJEbSlOiZeMKvE/CX128Q0uWpUOT3SgIbZY7oLb2Pgtvk3D81dGd3Pt9gc9MEUyfjLzU17jtUHxylrJQcCjoeJz7/uF3pNAUxEdYnKJ2fGo7eMW4DughNRUX7zSDcHgOIkZGnqK6GwPc6h9J2OXxsJC+SiuYHrPClE4cBxHdeNkAcMzETiJ7ZQYe3Pz21oVaXkbJYj+gSW1TQqEVYUOxPYwGlknkZJu17LBVkYLdDBqOzsMwKs/lTDJa7HRWg/5hDytW2YPK1pNOENs8/6Szew6Sf7mJhBy5UYoCp6A7p9WT4RkNekYrD3CZQ5UDcI3s8pVQ3ggbpJqEeZKwcWuLoN3TNvyN0pHCyrEfqNc/J2mTPrDA6sAzO64DyTBfRScZ/957wanyVyoiFc7l3NQEU/g3jcW61I1HIdBpiRhhuvUqJQGvfKOHiyEum5Vfi+hKRJ9h8xMHem4LAGCkIfyqUCDRaYeMq06FrujdOYWkwf5TNOHFvLKftb2QbUl1z9+7NjER/znjlc5DaYKwK38MeYpS/rgzTRqriuv32B+g/s9quGk8Ih6k2cd2UraucYhNLwOPW+oYpLsV3n/GuuMclU=
  - secure: PnC9np14fFGQSVKsxDg0rLE/XSEXqMKrzo9KAiEFQOx65Uud/IV7BeVkKMBP1PMq0shDxTtDASErufJg+Y5Pq/ztBezJBDlO3u6CKQycToo/gLOkJjifpHlpfj3o26iY3obFrTaq1uPgZSOjnN5mGHZ6PquDgxS9VtisDHtk8FoV3wCK5+E/Eu+UAW2o8aKZQCF6bTX/sAH4O5J3mfjEPrgj7RrDEM518JKiifRfd1Q/XGr4yZZ98x5C4q9uGOzTmmIGXmMhObKrIbnyOBZveO+aWmU3lBWFZwZr/Ab+v7vnSCUpWzbZ7VCaTQX/0IRL0QWZRmnWCL1H6fu8IwTgE3tAZD28QGNN6wYtJL98wXJJhBLSQeGGyS2ETTVEPcIRrpGlA8e9iRMfyOfVjyeTMFCSytClsNivxiiuLH1fOpten3aWA5I+6Aa7smkj3VEuik+lHeyIt5FuNy+uK4ROJbflUwOOltDUUqOFfCNNiGfYWpoCzi65LA6OmNX3OW74vwQYCJHef2VCPDUhft4Miggr6215qtxWMp0oAtAIDbJOrrranLzIahtJhNZR1q+LQXoYmHIx2TAuDEqBxMYt/Wlfotj4ObvusEDS9StcxVEMw9W1H1+7nH6LG+r562NmRfuySa03wMhatkWWWvCLHuC5bYP4SsR/nTkVugAyI4I=
